version: '3'

services:
  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - './scripts/create_db.sql:/docker-entrypoint-initdb.d/1.sql'
      - './scripts/create_table.sql:/docker-entrypoint-initdb.d/2.sql'
      - './scripts/create_data.sql:/docker-entrypoint-initdb.d/3.sql'
      - './scripts/select_data.sql:/docker-entrypoint-initdb.d/4.sql'
